numbers = [1,2,5,3,4,5,6]
#numbers.append(7)
#numbers.insert(1,21)
#numbers.remove(2)
#numbers.clear()
#numbers.pop()
#print(f"Index: {numbers.index(2)}")
#print(5 in numbers)
#print(numbers.count(5))
#numbers.sort()
#numbers.reverse()
numbers2 = numbers.copy()
numbers.append(21)
print(numbers)
print(numbers2)